source("test/ablation-03/scripts/helpers/stage_receipt_helpers.R")
stage <- tempfile("stage-")
dir.create(stage)
input <- file.path(stage, "input.txt")
output <- file.path(stage, "output.txt")
writeLines("original", input)
writeLines("result", output)
.ae_write_stage_receipt(stage, input, output)
stopifnot(isTRUE(.ae_validate_stage_receipt(stage)))
writeLines("changed", input)
error <- tryCatch({.ae_validate_stage_receipt(stage); NULL}, error = identity)
stopifnot(inherits(error, "error"))
cat("stage provenance tests passed\n")
