# Purpose: Deliver vector PDF figures and deterministic JPG previews.
# Input: One-page PDF paths generated by the ablation Rmd.
# Parameters: Preview directory and DPI exposed through Rmd YAML params.
# Output: JPG files with the same aspect ratio as their source PDFs.

bensz_run_dir <- function(root_dir, prefix = "ablation-experiment") {
  dir.create(root_dir, recursive = TRUE, showWarnings = FALSE)
  run_dir <- file.path(
    root_dir,
    paste0(prefix, "-", format(Sys.time(), "%Y%m%d%H%M%S"))
  )
  if (dir.exists(run_dir)) {
    run_dir <- paste0(run_dir, "-", Sys.getpid())
  }
  dir.create(run_dir, recursive = TRUE, showWarnings = FALSE)
  normalizePath(run_dir, winslash = "/", mustWork = TRUE)
}

bensz_preview_root <- function(configured = NULL) {
  if (!is.null(configured) && length(configured) == 1L && nzchar(configured)) {
    return(configured)
  }
  task_root <- Sys.getenv("BENSZ_TASK_ROOT", unset = "")
  if (nzchar(task_root)) return(file.path(task_root, "bensz-rmd-rules", "output", "plot-previews"))
  .wf_output("plot-previews")
}

bensz_pdf_to_jpg <- function(pdf_path, jpg_path, dpi = 200L) {
  dir.create(dirname(jpg_path), recursive = TRUE, showWarnings = FALSE)
  if (file.exists(jpg_path)) {
    unlink(jpg_path)
  }
  pdftools::pdf_convert(
    pdf = pdf_path,
    pages = 1L,
    dpi = as.integer(dpi),
    filenames = jpg_path,
    format = "jpeg"
  )
  if (!file.exists(jpg_path)) {
    stop("Failed to create JPG preview: ", jpg_path, call. = FALSE)
  }
  normalizePath(jpg_path, winslash = "/", mustWork = TRUE)
}
